import React from 'react';
import jsPDF from 'jspdf';

const PDFExport = ({ playerData }) => {
    const generatePDF = () => {
        if (!playerData) {
            alert('No player data to export');
            return;
        }

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        let yPos = 20;

        doc.setFillColor(102, 126, 234);
        doc.rect(0, 0, pageWidth, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('MicroMentor', pageWidth / 2, 20, { align: 'center' });
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text('Player Development Report', pageWidth / 2, 30, { align: 'center' });

        yPos = 55;
        doc.setTextColor(51, 51, 51);

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(`Player: ${playerData.profile?.name || 'Unknown'}`, 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text(`Team: ${playerData.profile?.team || 'N/A'}  |  Role: ${playerData.profile?.role?.toUpperCase() || 'N/A'}`, 20, yPos);
        yPos += 5;
        doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 20, yPos);
        yPos += 15;

        doc.setDrawColor(102, 126, 234);
        doc.setLineWidth(0.5);
        doc.line(20, yPos, pageWidth - 20, yPos);
        yPos += 15;

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Performance Overview', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        if (playerData.skills?.categories) {
            playerData.skills.categories.forEach(category => {
                doc.setFont('helvetica', 'bold');
                doc.text(`${category.name}: ${category.score}/100`, 25, yPos);
                yPos += 6;

                if (category.skills) {
                    doc.setFont('helvetica', 'normal');
                    category.skills.forEach(skill => {
                        doc.text(`  • ${skill.name}: ${skill.value} (${skill.percentile}th percentile)`, 30, yPos);
                        yPos += 5;
                    });
                }
                yPos += 3;
            });
        }

        yPos += 10;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('AI Coach Insights', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        if (playerData.insights && playerData.insights.length > 0) {
            playerData.insights.slice(0, 3).forEach((insight, idx) => {
                const lines = doc.splitTextToSize(`${idx + 1}. ${insight.data}`, pageWidth - 50);
                lines.forEach(line => {
                    doc.text(line, 25, yPos);
                    yPos += 5;
                });

                if (insight.insight) {
                    const insightLines = doc.splitTextToSize(`   → ${insight.insight}`, pageWidth - 55);
                    doc.setTextColor(102, 126, 234);
                    insightLines.forEach(line => {
                        doc.text(line, 25, yPos);
                        yPos += 5;
                    });
                    doc.setTextColor(51, 51, 51);
                }

                doc.text(`   Confidence: ${insight.confidence}%`, 25, yPos);
                yPos += 8;
            });
        }

        yPos += 10;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Improvement Goals', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        if (playerData.improvementPlan?.goals) {
            playerData.improvementPlan.goals.forEach(goal => {
                doc.text(`• ${goal.title}`, 25, yPos);
                yPos += 5;
                doc.text(`  Current: ${goal.current}%  →  Target: ${goal.target}%  (Progress: ${goal.progress}%)`, 30, yPos);
                yPos += 8;
            });
        }

        doc.setFillColor(240, 240, 240);
        doc.rect(0, doc.internal.pageSize.getHeight() - 20, pageWidth, 20, 'F');
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text('Generated by MicroMentor - AI-Powered Player Development Platform', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

        doc.save(`micromentor_report_${playerData.profile?.name || 'player'}_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    return (
        <button className="export-btn" onClick={generatePDF}>
            📄 Export PDF Report
        </button>
    );
};

export default PDFExport;
